### ISSUE TITLE
Not working on Sketch 45.2

### ISSUE THREAD

**Issue by EmanuelMilicevic** [daneden/sketch-replace-layer#2]
I really love this plugin. It's a time saver. But in Sketch 45.2 this plugin only paste layer above selected.

**Comment by malykh** [comment]
+1

Please make an update. Your plugin is a gold!

**Comment by emarvegt** [comment]
Indeed. Not working in recent versions since 45.2. Please update, I really like this plugin!

**Comment by shnhrrsn** [comment]
Not to pile on, but still broken in 48… Hope you can find some time to fix it 🙏🏻

**Comment by whoisjuan** [comment]
This is a good plugin. It would be great if you can fix it.

**Comment by daneden** [comment]
Hey all! Sorry I've been slow to fix this, here are my honest reasons:

- I don't use Sketch all that much any more—I don't use it _at all_ on my personal computer so testing has been hard!
- Sketch’s API changes in mysterious ways. The code currently used to allow this plugin to run has been removed since about v45 and I've been trying to figure out the right approach to fix it.

I'm working on a fix and will try not to let Real Life intervene much more!

**Comment by daneden** [comment]
This should now be fixed by c3ea2845b6fce7c34ce51aa306c2212b83f90c01! Thanks for your patience everyone. I'm now working on getting the plugin to use Sketch's new plugin update system, but for the time being, you'll need to re-install from the repo.
